### ISSUE TITLE
SoftwareSerial not working with XBee

### ISSUE THREAD

**Issue by ClintonKeith** [andrewrapp/xbee-arduino#13]
I have the 1.6.5 IDE and the latest (10/6) XBee library.  When I try to connect my XBee with a SoftSerial interface, the Uno is resetting.

I use the following in Series2_Tx setup:
  SoftwareSerial mySerial(8,9); // RX, TX
  mySerial.begin(9600);
  xbee.setSerial(mySerial);   

and as soon as xbee.send(zbTx); is called the Uno reboots.

**Comment by davidsainty** [comment]
Looks like mySerial is a local variable in setup ()?

Make it a global.

On 13/10/2015 5:40 PM, "ClintonKeith" <notifications@github.com> wrote:
>
> I have the 1.6.5 IDE and the latest (10/6) XBee library. When I try to
connect my XBee with a SoftSerial interface, the Uno is resetting.

**Comment by matthijskooijman** [comment]
@davidsainty seems to point out the cause of your error.

Additionally, you might want to consider using the AltSoftSerial library, which is a lot more reliable and can do full-duplex communication as well (e.g. receive while transmitting), which SoftwareSerial doesn't. It's limitation is that it only works on pin 8 and 9 (on a Uno), but it seems you're already using those anyway.

**Comment by ClintonKeith** [comment]
Ugh.  Well I guess I picked the wrong week to start sniffing glue.

Thanks for catching my blunder and the advice on AltSoftSerial.
