### ISSUE TITLE
Is it possible to programmatically modify the configuration values of the Xbee? 

### ISSUE THREAD

**Issue by sdiaz-qkt** [andrewrapp/xbee-arduino#76]
Hello, 

I was wondering if it was possible to change the DL and DE values of the Xbee configuration without using XCTU, and instead, using this library. 
So far I have been able to only read the parameters, and I can't seem to find any documentation to help me do this. 

Thanks in advance for the help.

**Comment by JChristensen** [comment]
Yes. Use an AtCommandRequest object to query or set parameters. Plan to spend some time with the documentation that comes with the library and also with the XBee User's Guide [(for example.)](https://www.digi.com/resources/documentation/digidocs/pdfs/90002002.pdf) I found it useful to read the User Guide frame descriptions (e.g. AT Command frame 0x08) along with the relevant class from the library.
Destination address is part of the transmit request frame (frame type 0x10, use the ZBTxRequest class), so it's not necessary to set the destination for each transmission via an AT command.
