### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by Ruudjhuu** [andrewrapp/xbee-arduino#81]
Question is in title, last commit was in dec 2016 for the README.md file.

**Comment by davidsainty** [comment]
It doesn't need a lot of maintenance.  It's a microcontroller library, so size is more important than ever-increasing features...

**Comment by JChristensen** [comment]
Still works very nicely for me.

**Comment by Ruudjhuu** [comment]
It doesn't work for me. I'm not talking about increasing features. Only asking if bug reports are going to be fixed. I know it doesn't need a lot of maintenance but it needs some. Still no answer on my question.

**Comment by JChristensen** [comment]
If it doesn't work for you, then I'd raise an issue describing the specific problem. There are some good guidelines at http://www.sscce.org/
